const EMAIL_PASS = 'AnimeWars1337!';
const { PORT, ROOT } = require('../app');
const FRONTEND_LOGGER_INTERVAL = 1000;
// cookies
const MAX_ASSETS_AGE = 365 * 24 * 60 * 60;
const MAX_UPLOADS_AGE = 365 * 24 * 60 * 60;
// indexController
const MAX_SEARCH_INPUT_LEN = 100;
const MIN_SEARCH_INPUT_LEN = 1;
const RECORDS_PER_PAGE = 40;
const MAX_RECORDS_PER_PAGE = 100;
// usersController
const MAX_USER_EMAIL_LEN = 50;
const MIN_USER_EMAIL_LEN = 5;
const MAX_USER_PASSWORD_LEN = 255;
const MIN_USER_PASSWORD_LEN = 8;
const MAX_USER_NAME_LEN = 20;
const MIN_USER_NAME_LEN = 2;
const CONNECTION_LIMIT = 1000;
const SERVICE_EMAIL = 'anime.cards.board@gmail.com';
const SERVICE_EMAIL_PROVIDER = 'gmail';
// backOfficeController
const MAX_USERNAME_LEN = 20;
const MAX_SEARCH_FILTER_LEN = 50;

module.exports = {
  EMAIL_PASS: EMAIL_PASS,
  PORT: PORT,
  ROOT: ROOT,
  FRONTEND_LOGGER_INTERVAL: FRONTEND_LOGGER_INTERVAL,
  MAX_ASSETS_AGE: MAX_ASSETS_AGE,
  MAX_UPLOADS_AGE: MAX_UPLOADS_AGE,
  MAX_SEARCH_INPUT_LEN: MAX_SEARCH_INPUT_LEN,
  MIN_SEARCH_INPUT_LEN: MIN_SEARCH_INPUT_LEN,
  RECORDS_PER_PAGE: RECORDS_PER_PAGE,
  MAX_RECORDS_PER_PAGE: MAX_RECORDS_PER_PAGE,
  MAX_USER_EMAIL_LEN: MAX_USER_EMAIL_LEN,
  MIN_USER_EMAIL_LEN: MIN_USER_EMAIL_LEN,
  MAX_USER_PASSWORD_LEN: MAX_USER_PASSWORD_LEN,
  MIN_USER_PASSWORD_LEN: MIN_USER_PASSWORD_LEN,
  MAX_USER_NAME_LEN: MAX_USER_NAME_LEN,
  MIN_USER_NAME_LEN: MIN_USER_NAME_LEN,
  CONNECTION_LIMIT: CONNECTION_LIMIT,
  SERVICE_EMAIL: SERVICE_EMAIL,
  SERVICE_EMAIL_PROVIDER: SERVICE_EMAIL_PROVIDER,
  MAX_USERNAME_LEN: MAX_USERNAME_LEN,
  MAX_SEARCH_FILTER_LEN: MAX_SEARCH_FILTER_LEN,
};
