const EMAIL_PASS = 'AnimeWars1337!';
const { PORT, ROOT } = require('../app');
const FRONTEND_LOGGER_INTERVAL = 1000;
// cookies
const MAX_ASSETS_AGE = 365 * 24 * 60 * 60;
const MAX_UPLOADS_AGE = 365 * 24 * 60 * 60;
//db;
const PGUSER = 'velioo';
const PGDATABASE = 'anime_cb';
const IDLE_TIMEOUT_MILLIS = 30000;
const CONNECTION_LIMIT = 1000;
// indexController
const MAX_SEARCH_INPUT_LEN = 100;
const MIN_SEARCH_INPUT_LEN = 1;
const RECORDS_PER_PAGE = 40;
const MAX_RECORDS_PER_PAGE = 100;
// usersController
const MAX_USER_EMAIL_LEN = 50;
const MIN_USER_EMAIL_LEN = 5;
const MAX_USER_PASSWORD_LEN = 255;
const MIN_USER_PASSWORD_LEN = 8;
const MAX_USER_NAME_LEN = 20;
const MIN_USER_NAME_LEN = 3;
const SERVICE_EMAIL = 'anime.cards.board@gmail.com';
const SERVICE_EMAIL_PROVIDER = 'gmail';
// roomController
const MIN_ROOM_NAME_LEN = 3;
const MAX_ROOM_NAME_LEN = 20;

const TURN_PHASES = {
  DRAW: 1,
  STANDBY: 2,
  MAIN: 3,
  ROLL: 4,
  END: 5,
};

const CARD_RARITIES = {
  COMMON: 'common',
  RARE: 'rare',
  EPIC: 'epic',
};

const CARD_RARITIES_COEF = {
  COMMON: 1,
  RARE: 2,
  EPIC: 4,
};

const BOARD_FIELDS = {
  NORMAL: 1,
  ROLL_AGAIN_1: 2,
  ROLL_AGAIN_2: 3,
  ROLL_AGAIN_3: 4,
  ROLL_AGAIN_BACKWARDS_1: 5,
  CARD_DRAW_1: 6,
  CARD_DRAW_2: 7,
  CARD_DRAW_3: 8,
  CARD_DISCARD_1: 9,
  CARD_DISCARD_2: 10,
  CARD_DISCARD_3: 11,
  RANDOM_1: 12,
  RANDOM_2: 13,
  RANDOM_3: 14,
  ROLL_AGAIN_BACKWARDS_2: 15,
  ROLL_AGAIN_BACKWARDS_3: 16,
  ENERGY_GAIN_1: 17,
  ENERGY_GAIN_2: 18,
  ENERGY_GAIN_3: 19,
  ENERGY_LOSE_1: 20,
  ENERGY_LOSE_2: 21,
  ENERGY_LOSE_3: 22,
};

module.exports = {
  EMAIL_PASS: EMAIL_PASS,
  PORT: PORT,
  ROOT: ROOT,
  PGUSER,
  PGDATABASE,
  IDLE_TIMEOUT_MILLIS,
  CONNECTION_LIMIT: CONNECTION_LIMIT,
  FRONTEND_LOGGER_INTERVAL: FRONTEND_LOGGER_INTERVAL,
  MAX_ASSETS_AGE: MAX_ASSETS_AGE,
  MAX_UPLOADS_AGE: MAX_UPLOADS_AGE,
  MAX_SEARCH_INPUT_LEN: MAX_SEARCH_INPUT_LEN,
  MIN_SEARCH_INPUT_LEN: MIN_SEARCH_INPUT_LEN,
  RECORDS_PER_PAGE: RECORDS_PER_PAGE,
  MAX_RECORDS_PER_PAGE: MAX_RECORDS_PER_PAGE,
  MAX_USER_EMAIL_LEN: MAX_USER_EMAIL_LEN,
  MIN_USER_EMAIL_LEN: MIN_USER_EMAIL_LEN,
  MAX_USER_PASSWORD_LEN: MAX_USER_PASSWORD_LEN,
  MIN_USER_PASSWORD_LEN: MIN_USER_PASSWORD_LEN,
  MAX_USER_NAME_LEN: MAX_USER_NAME_LEN,
  MIN_USER_NAME_LEN: MIN_USER_NAME_LEN,
  SERVICE_EMAIL: SERVICE_EMAIL,
  SERVICE_EMAIL_PROVIDER: SERVICE_EMAIL_PROVIDER,
  MIN_ROOM_NAME_LEN: MIN_ROOM_NAME_LEN,
  MAX_ROOM_NAME_LEN: MAX_ROOM_NAME_LEN,
  TURN_PHASES: TURN_PHASES,
  CARD_RARITIES: CARD_RARITIES,
  CARD_RARITIES_COEF: CARD_RARITIES_COEF,
  BOARD_FIELDS: BOARD_FIELDS,
};
